name: Api - Build and Test

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.803
      - name: Build
        run: |
          pushd api
          dotnet restore
          dotnet build
          popd
      - name: Test
        run: |
          pushd api
          dotnet test
          popd
